version: '3.5'
networks:
  pm:
    driver: bridge
services: 
  backend:
    container_name: backend
    networks:
      - pm
    ports:
      - 9000:9000
    build:
      context: ./backend
      dockerfile: Dockerfile.PlayFramework
    volumes:
      - ./backend/src:/opt